#!/usr/bin/env node

/**
 * Dependencies
 */

var fs = require('fs');
var path = require('path');

/**
 * Options
 */

startDir = process.argv[2];

/**
 * Define functions
 */

// recursive search a la *nix find

function find(startDir, cb) {
  var uniqueYears = [];
  var uniqueMonths = [];
  var uniqueYYMMs = [];
  var uniqueYYMMsObj = {};
  var fileCnt = 1;
  var asyncRunning = 0;

  function dirOrFile (dirFile) {
    // async function
    fs.stat(dirFile, function(err, stats) {
      if (err) throw err;
      // if directory, call find again on all files within the directory
      if (stats.isDirectory()) {
        fileCnt--;
        asyncRunning++;
        // another async function
        fs.readdir(dirFile, function(err, files) {
          asyncRunning--;
          if (err) throw err;
          fileCnt += files.length;
          for(var i = 0; i < files.length; i++) {
            dirOrFile(path.join(dirFile, files[i])); // recurse
          }
        });
      } else if (stats.isFile()) {
        fileCnt--;
        year = stats['mtime'].getFullYear();
        month = ('0' + (stats['mtime'].getMonth()+1)).slice(-2);
        yymm = year + '-' + month;

        console.log('file: ' + dirFile);
        console.log('year: ' + year); 
        console.log('month: ' + month);
        console.log();

        if (!(year in uniqueYYMMsObj)) {
          // object with 'year' property equal to
          // an array containing the month
          // uniqueYYMMsObj = {year: [month]};
          // console.log('hahaha ' + uniqueYYMMsObj);
        }
        if (uniqueYYMMs.indexOf(yymm) === -1) {
          uniqueYYMMs.push(yymm);
        }
        if (uniqueYears.indexOf(year) === -1) {
          uniqueYears.push(year);
        }
        if (uniqueMonths.indexOf(month) === -1) {
          uniqueMonths.push(month);
        }
      } else {
        fileCnt--;
      }
      if (fileCnt === 0 && asyncRunning === 0) {
        cb(uniqueYears.sort(), uniqueMonths.sort(), uniqueYYMMs.sort());
      }
    });
  }
  dirOrFile(startDir);
}

function printUniques(arr, label) {
  console.log('Unique ' + label + '...');
  for (var i = 0; i < arr.length; i++) {
    console.log(arr[i]);
  }
  console.log();
}

function uniques(uniqueYears, uniqueMonths, uniqueYYMMs) {
  printUniques(uniqueYears, 'years');
  printUniques(uniqueMonths, 'months');
  printUniques(uniqueYYMMs, 'YYMMs');
}

find(startDir, uniques);
