#!/usr/bin/env node

/**
 * Dependencies
 */

var fs = require('fs');
var path = require('path');

/**
 * Options
 */

startDir = process.argv[2];

/**
 * Define functions
 */

// recursive search a la *nix find

function find(startDir, cb) {
  var uniqueYears = [];
  var uniqueMonths = [];
  var fileCnt = 1;
  var asyncRunning = 0;

  function dirOrFile (dirFile) {
    // async function
    fs.stat(dirFile, function(err, stats) {
      if (err) throw err;
      // if directory, call find again on all files within the directory
      if (stats.isDirectory()) {
        fileCnt--;
        asyncRunning++;
        // another async function
        fs.readdir(dirFile, function(err, files) {
          asyncRunning--;
          if (err) throw err;
          fileCnt += files.length;
          for(var i = 0; i < files.length; i++) {
            dirOrFile(path.join(dirFile, files[i])); // recurse
          }
        });
      } else if (stats.isFile()) {
        fileCnt--;
        year = stats['mtime'].getFullYear();
        month = stats['mtime'].getMonth();

        console.log('file: ' + dirFile);
        console.log('year: ' + year); 
        console.log('month: ' + month);
        console.log();

        if (uniqueYears.indexOf(year) === -1) {
          uniqueYears.push(year);
        }
        if (uniqueMonths.indexOf(month) === -1) {
          uniqueMonths.push(month);
        }
      } else {
        fileCnt--;
      }
      if (fileCnt === 0 && asyncRunning === 0) {
        cb(uniqueYears, uniqueMonths);
      }
    });
  }
  dirOrFile(startDir);
}

function uniques(uniqueYears, uniqueMonths) {
  console.log('Unique years...');
  for (var i = 0; i < uniqueYears.length; i++) {
    console.log(uniqueYears[i]);
  }
  console.log('Unique months...');
  for (var j = 0; j < uniqueMonths.length; j++) {
    console.log(uniqueMonths[j]);
  }
}

find(startDir, uniques);
